"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useActiveClient } from "@/components/active-client";
import { TrendingUp, TrendingDown, ThumbsUp, ThumbsDown, FileText } from "lucide-react";
import { getWeeklyBrief, type WeeklyBrief } from "@/lib/api";
import { useClientList } from "@/components/client-select";
import { StatCard, XpProgress, Loading, ErrorNote } from "@/components/xp";
import { AppToolbar } from "@/components/apps/app-toolbar";

function daysUntilMonday(): number {
  const day = new Date().getDay(); // 0=Sun..6=Sat
  const d = (8 - day) % 7;
  return d === 0 ? 7 : d;
}

function fmtDate(s?: string): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return s;
  }
}

function asList(v: unknown): string[] {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) {
    try {
      const p = JSON.parse(v);
      if (Array.isArray(p)) return p.map(String);
    } catch { /* not json */ }
    return [v];
  }
  return [];
}

function EmptyState() {
  const d = daysUntilMonday();
  return (
    <div className="card-flush mx-auto my-8 w-[440px] max-w-full">
      <div className="card-header">No Weekly Brief Yet</div>
      <div className="space-y-3 px-5 py-5">
        <div className="flex items-center gap-3">
          <FileText size={30} className="text-[var(--accent)]" />
          <div className="text-[13px] text-[var(--foreground)]">
            No weekly brief yet. The Synthesis Agent runs <strong>Monday 9 AM IST</strong>.
            <div className="mt-0.5 text-[12px] text-[var(--text-secondary)]">Next brief in {d} day{d === 1 ? "" : "s"}.</div>
          </div>
        </div>
        <div>
          <div className="mb-1 flex justify-between text-[10px] uppercase tracking-wide text-[var(--text-secondary)]">
            <span>This week</span><span>Monday</span>
          </div>
          <XpProgress value={((7 - d) / 7) * 100} tone="teal" showValue />
        </div>
      </div>
    </div>
  );
}

function BriefBody({ b }: { b: WeeklyBrief }) {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Moved forward" value={b.accounts_moved_forward} accent="#15803d" icon={<TrendingUp size={14} />} />
        <StatCard label="Stalled" value={b.accounts_stalled} accent="#b45309" icon={<TrendingDown size={14} />} />
        <StatCard label="Best angle" value={<span className="text-[15px]">{b.best_angle ?? "—"}</span>} accent="#0f766e" icon={<ThumbsUp size={14} />} />
        <StatCard label="Worst angle" value={<span className="text-[15px]">{b.worst_angle ?? "—"}</span>} accent="#dc2626" icon={<ThumbsDown size={14} />} />
      </div>

      {/* Orchestrator guidance — styled like a real memo the system wrote */}
      <div className="card-flush">
        <div className="card-header">Orchestrator Guidance</div>
        <div
          className="px-6 py-5 text-[15px] leading-relaxed text-[var(--foreground)]"
          style={{ background: "#fbfaf4", fontFamily: "Georgia, 'Times New Roman', serif" }}
        >
          {b.orchestrator_guidance ? (
            <p className="whitespace-pre-wrap">{b.orchestrator_guidance}</p>
          ) : (
            <p className="italic text-[var(--text-secondary)]">No guidance recorded for this week.</p>
          )}
        </div>
      </div>

      {asList(b.icp_refinement_suggestions).length > 0 && (
        <div className="card-flush">
          <div className="card-header">ICP Refinement</div>
          <ul className="list-disc space-y-1 px-8 py-3 text-[13px] text-[var(--foreground)]">
            {asList(b.icp_refinement_suggestions).map((s, i) => <li key={i}>{s}</li>)}
          </ul>
        </div>
      )}

      {b.recommended_focus && (
        <div className="rounded-md border-l-4 border-[var(--accent)] bg-[var(--accent-soft)] px-4 py-3">
          <div className="text-[10px] font-semibold uppercase tracking-wide text-[var(--accent)]">Recommended Focus</div>
          <div className="text-[15px] font-semibold text-[var(--foreground)]">{b.recommended_focus}</div>
        </div>
      )}

      <div className="text-right text-[11px] italic text-[var(--text-secondary)]">
        Generated by Weekly Synthesis Agent — {fmtDate(b.created_at)}
      </div>
    </div>
  );
}

export default function WeeklyBriefApp() {
  const { data: clients, isLoading, error } = useClientList();
  const { activeClientId, setActiveClientId } = useActiveClient();
  const clientId = activeClientId ?? clients?.[0]?.id ?? null;
  const [weekId, setWeekId] = useState<string | null>(null);

  const brief = useQuery({
    queryKey: ["weekly-brief", clientId],
    queryFn: () => getWeeklyBrief(clientId!),
    enabled: !!clientId,
  });

  const history = brief.data?.history ?? [];
  const selected = useMemo(
    () => history.find((h) => h.id === weekId) ?? brief.data?.latest ?? null,
    [history, weekId, brief.data],
  );

  if (isLoading) return <Loading label="Loading clients…" />;
  if (error) return <ErrorNote error={error} />;
  if (!clients || clients.length === 0)
    return <p className="py-6 text-center text-[13px] text-neutral-500">No clients yet.</p>;

  return (
    <div className="space-y-4 p-4">
      <AppToolbar
        clients={clients}
        value={clientId}
        onChange={(id) => { setActiveClientId(id); setWeekId(null); }}
        right={
          history.length > 0 && (
            <select className="xp-app-select" value={weekId ?? selected?.id ?? ""} onChange={(e) => setWeekId(e.target.value)}>
              {history.map((h) => (
                <option key={h.id} value={h.id}>Week of {fmtDate(h.week_of)}</option>
              ))}
            </select>
          )
        }
      />

      {brief.isLoading ? (
        <Loading label="Loading brief…" />
      ) : brief.error ? (
        <ErrorNote error={brief.error} />
      ) : selected ? (
        <BriefBody b={selected} />
      ) : (
        <EmptyState />
      )}
    </div>
  );
}
